[package]
name = "githelper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.0"
git2 = "0.16.1"
tinyfiledialogs = "3.9.1"
tracing-subscriber = "0.3.16"
